#
# Makefile for the Linux Kernel SOC specific device drivers.
#

obj-$(CONFIG_SOC_BRCMSTB)	+= brcmstb/
obj-$(CONFIG_MACH_DOVE)		+= dove/
obj-$(CONFIG_SOC_MEDIATEK)	+= mediatek/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_ARCH_ROCKCHIP)		+= rockchip/
obj-$(CONFIG_ARCH_SUNXI)	+= sunxi/
obj-$(CONFIG_ARCH_TEGRA)	+= tegra/
obj-$(CONFIG_SOC_TI)		+= ti/
obj-$(CONFIG_PLAT_VERSATILE)	+= versatile/

#ifdef VENDOR_EDIT
# Bin.Li@EXP.BSP.bootloader.bootflow, 2017/05/15, Add for oppo device info and oppo project
obj-$(CONFIG_OPPO_ARCH_FILE)	+= oppo/
#endif /*VENDOR_EDIT*/
